/**
 * GentCoDesign - Export Pipeline
 * Export designs to: HTML, PDF, PPTX, ZIP, Markdown, PNG
 */

const fs = require('fs');
const path = require('path');
const archiver = require('archiver');
const config = require('../core/config');

class ExportPipeline {
  constructor() {
    this.exportDir = config.paths().exports;
  }

  /**
   * Export a design to specified format
   * @param {Object} opts
   * @param {string} opts.designId - Design ID
   * @param {string} opts.html - HTML content
   * @param {string} opts.format - 'html' | 'pdf' | 'pptx' | 'zip' | 'md' | 'png'
   * @param {string} opts.outputPath - Custom output path
   * @param {Object} opts.metadata - Design metadata
   * @returns {Promise<string>} Output file path
   */
  async export(opts) {
    const { html, format = 'html', outputPath, metadata = {} } = opts;

    const outDir = outputPath || this.exportDir;
    if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

    const baseName = this._sanitizeName(metadata.prompt || 'design');

    switch (format) {
      case 'html':
        return this._exportHtml(html, outDir, baseName, metadata);
      case 'pdf':
        return this._exportPdf(html, outDir, baseName);
      case 'pptx':
        return this._exportPptx(html, outDir, baseName, metadata);
      case 'zip':
        return this._exportZip(html, outDir, baseName, metadata);
      case 'md':
        return this._exportMarkdown(html, outDir, baseName, metadata);
      case 'png':
        return this._exportPng(html, outDir, baseName);
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Export as standalone HTML file (inlined CSS)
   */
  _exportHtml(html, outDir, baseName, metadata) {
    // Wrap in a complete HTML document if needed
    let fullHtml = html;
    if (!fullHtml.includes('<!DOCTYPE') && !fullHtml.includes('<html')) {
      fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this._escapeHtml(metadata.prompt || 'GentCoDesign Export')}</title>
</head>
<body>
${fullHtml}
</body>
</html>`;
    }

    // Add metadata comment
    const metaComment = `<!--
  Generated by GentCoDesign v1.0
  Design ID: ${metadata.id || 'N/A'}
  Prompt: ${metadata.prompt || 'N/A'}
  Skills: ${(metadata.skills || []).join(', ')}
  Model: ${metadata.model || 'N/A'}
  Created: ${metadata.createdAt || new Date().toISOString()}
-->
`;
    fullHtml = fullHtml.replace(/<!DOCTYPE/i, metaComment + '<!DOCTYPE');

    const outPath = path.join(outDir, `${baseName}.html`);
    fs.writeFileSync(outPath, fullHtml);
    return outPath;
  }

  /**
   * Export as PDF using Puppeteer
   */
  async _exportPdf(html, outDir, baseName) {
    let puppeteer;
    try {
      puppeteer = require('puppeteer');
    } catch (e) {
      throw new Error('PDF export requires puppeteer. Install with: npm install puppeteer');
    }

    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0', timeout: 30000 });
      await page.setViewport({ width: 1440, height: 900 });

      const outPath = path.join(outDir, `${baseName}.pdf`);
      await page.pdf({
        path: outPath,
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
      });
      return outPath;
    } finally {
      await browser.close();
    }
  }

  /**
   * Export as PowerPoint presentation
   */
  async _exportPptx(html, outDir, baseName, metadata) {
    let PptxGenJS;
    try {
      PptxGenJS = require('pptxgenjs');
    } catch (e) {
      throw new Error('PPTX export requires pptxgenjs. Install with: npm install pptxgenjs');
    }

    // Take screenshot first, then embed in slides
    let puppeteer;
    try {
      puppeteer = require('puppeteer');
    } catch (e) {
      throw new Error('PPTX export requires puppeteer for screenshots.');
    }

    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox']
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0', timeout: 30000 });
      await page.setViewport({ width: 1440, height: 900 });

      // Get full page screenshot
      const screenshot = await page.screenshot({
        type: 'png',
        fullPage: true,
        encoding: 'base64'
      });

      const pptx = new PptxGenJS();
      pptx.author = 'GentCoDesign';
      pptx.title = metadata.prompt || 'Design Export';

      // Title slide
      const titleSlide = pptx.addSlide();
      titleSlide.addText(metadata.prompt || 'Design', {
        x: 0.5, y: 1, w: 9, h: 1.5,
        fontSize: 36, bold: true, color: 'FFFFFF',
        align: 'center'
      });
      titleSlide.addText(`Generated by GentCoDesign\n${new Date().toLocaleDateString()}`, {
        x: 0.5, y: 3, w: 9, h: 1,
        fontSize: 14, color: 'CCCCCC', align: 'center'
      });
      titleSlide.background = { color: '1a1a2e' };

      // Design slide with screenshot
      const designSlide = pptx.addSlide();
      designSlide.addImage({
        data: `image/png;base64,${screenshot}`,
        x: 0.25, y: 0.25,
        w: 9.5, h: 7
      });

      // Details slide
      const detailsSlide = pptx.addSlide();
      detailsSlide.addText('Design Details', {
        x: 0.5, y: 0.5, w: 9, h: 0.8,
        fontSize: 28, bold: true, color: 'FFFFFF'
      });
      const details = [
        `Skills: ${(metadata.skills || []).join(', ')}`,
        `Model: ${metadata.model || 'N/A'}`,
        `Theme: ${metadata.theme || 'dark'}`,
        `Style: ${metadata.style || 'modern'}`,
        `Created: ${metadata.createdAt || new Date().toISOString()}`
      ];
      detailsSlide.addText(details.join('\n'), {
        x: 0.5, y: 1.5, w: 9, h: 4,
        fontSize: 16, color: 'CCCCCC', lineSpacingMultiple: 1.5
      });
      detailsSlide.background = { color: '1a1a2e' };

      const outPath = path.join(outDir, `${baseName}.pptx`);
      await pptx.writeFile({ fileName: outPath });
      return outPath;
    } finally {
      await browser.close();
    }
  }

  /**
   * Export as ZIP (HTML + assets)
   */
  async _exportZip(html, outDir, baseName, metadata) {
    const outPath = path.join(outDir, `${baseName}.zip`);
    const output = fs.createWriteStream(outPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    return new Promise((resolve, reject) => {
      output.on('close', () => resolve(outPath));
      archive.on('error', reject);

      archive.pipe(output);

      // Add HTML
      archive.append(html, { name: 'index.html' });

      // Add README
      const readme = `# ${metadata.prompt || 'GentCoDesign Export'}

Generated by GentCoDesign
Design ID: ${metadata.id || 'N/A'}
Model: ${metadata.model || 'N/A'}
Skills: ${(metadata.skills || []).join(', ')}
Created: ${metadata.createdAt || new Date().toISOString()}

## Usage
Open \`index.html\` in any modern browser.
`;
      archive.append(readme, { name: 'README.md' });

      // Add metadata JSON
      archive.append(JSON.stringify(metadata, null, 2), { name: 'metadata.json' });

      archive.finalize();
    });
  }

  /**
   * Export as Markdown
   */
  _exportMarkdown(html, outDir, baseName, metadata) {
    // Extract text content and structure from HTML
    const textContent = html
      .replace(/<style[\s\S]*?<\/style>/gi, '')
      .replace(/<script[\s\S]*?<\/script>/gi, '')
      .replace(/<[^>]+>/g, '\n')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    let md = `# ${metadata.prompt || 'Design Export'}\n\n`;
    md += `> Generated by GentCoDesign\n\n`;
    md += `- **Design ID:** ${metadata.id || 'N/A'}\n`;
    md += `- **Model:** ${metadata.model || 'N/A'}\n`;
    md += `- **Skills:** ${(metadata.skills || []).join(', ')}\n`;
    md += `- **Theme:** ${metadata.theme || 'dark'}\n`;
    md += `- **Created:** ${metadata.createdAt || new Date().toISOString()}\n\n`;
    md += `## Content\n\n${textContent.slice(0, 5000)}\n\n`;
    md += `## HTML Source\n\nThe full HTML source is available in the accompanying .html file.\n`;

    const outPath = path.join(outDir, `${baseName}.md`);
    fs.writeFileSync(outPath, md);
    return outPath;
  }

  /**
   * Export as PNG screenshot
   */
  async _exportPng(html, outDir, baseName) {
    let puppeteer;
    try {
      puppeteer = require('puppeteer');
    } catch (e) {
      throw new Error('PNG export requires puppeteer. Install with: npm install puppeteer');
    }

    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox']
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0', timeout: 30000 });
      await page.setViewport({ width: 1440, height: 900 });

      const outPath = path.join(outDir, `${baseName}.png`);
      await page.screenshot({ path: outPath, fullPage: true, type: 'png' });
      return outPath;
    } finally {
      await browser.close();
    }
  }

  _sanitizeName(name) {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50) || 'design';
  }

  _escapeHtml(str) {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  /**
   * List supported export formats
   */
  static formats() {
    return [
      { id: 'html', name: 'HTML File', ext: '.html', description: 'Standalone HTML with inlined CSS' },
      { id: 'pdf', name: 'PDF Document', ext: '.pdf', description: 'Print-ready PDF via headless Chrome' },
      { id: 'pptx', name: 'PowerPoint', ext: '.pptx', description: 'Presentation with design screenshots' },
      { id: 'zip', name: 'ZIP Archive', ext: '.zip', description: 'HTML + README + metadata' },
      { id: 'md', name: 'Markdown', ext: '.md', description: 'Text content with metadata' },
      { id: 'png', name: 'PNG Screenshot', ext: '.png', description: 'Full-page screenshot' }
    ];
  }
}

module.exports = new ExportPipeline();
module.exports.ExportPipeline = ExportPipeline;
